name: kaminari_wallet
description: Cross-platform Bitcoin Lightning Wallet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.0.0
  hive_flutter: ^0.2.1
  rxdart: ^0.22.2
  barcode_scan: ^1.0.0
  protobuf: ^0.14.3
  fixnum: ^0.10.9
  grpc: ^2.1.2
  path_provider: ^1.3.0
  qr_flutter: ^3.0.1
  pigment: ^1.0.3
  flutter_secure_storage: ^3.3.1+1
  font_awesome_flutter: ^8.5.0
  connectivity: ^0.4.4
  generic_bloc_provider: ^1.0.9
  jdenticon_flutter: ^0.0.1
  intl: ^0.15.8
  groovin_widgets: ^1.4.2
  datetime_picker_formfield: ^0.4.3
  animated_stream_list: ^0.0.4
  date_util: ^0.1.4
  sliver_fill_remaining_box_adapter: ^0.1.1
  qr_code_scanner: ^0.0.12
  image_picker: ^0.6.1+4
  shared_preferences: ^0.5.3+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_native_splash: ^0.1.8+2
  hive_generator: ^0.5.1
  build_runner: ^1.7.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/splash_icon.png
  color: "673ab7"

dependency_overrides:
  flutter_svg: ^0.14.1
  meta: ^1.1.7

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/tada.svg
  fonts:
    - family: RobotoMono
      fonts:
        - asset:  assets/fonts/RobotoMono-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages